import fs from 'node:fs';
import path from 'node:path';
import request from 'supertest';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { eq, sql } from 'drizzle-orm';
import type { RoleCode } from '@gs/shared';
import { createApp } from '../../app';
import { db, pool } from '../../db/client';
import { accountingRecords, cutStockItems } from '../../db/schema';
import { createUser, resetDb, seedBasics, TEST_PASSWORD } from '../../test/helpers';

const app = createApp();
const DATA = path.resolve(__dirname, '../../db/seed/data');
let basics: Awaited<ReturnType<typeof seedBasics>>;
let tokens: Partial<Record<RoleCode, string>> = {};

async function as(role: RoleCode) {
  if (!tokens[role]) {
    await createUser(role);
    const res = await request(app)
      .post('/api/v1/auth/login')
      .send({ email: `${role.toLowerCase()}@test.local`, password: TEST_PASSWORD });
    tokens[role] = res.body.accessToken as string;
  }
  return { Authorization: `Bearer ${tokens[role]}` };
}

function exportShipment(overrides: Record<string, unknown> = {}) {
  return {
    clientId: basics.jr.id,
    direction: 'EXPORT',
    transportMode: 'SEA',
    loadType: 'FCL',
    status: 'IN_PROGRESS',
    forwarderId: basics.fwd.id,
    clearancePortId: basics.port.id,
    destinationCountryIso2: 'US',
    hblNo: 'MAE26123456',
    bookingNo: 'BKG-88213',
    etd: '2026-08-01',
    eta: '2026-08-25',
    containers: [
      { containerNo: 'mrku 897430-3', size: '40HQ', linerSeal: 'LS-4471', customsSeal: 'CS-9021' },
    ],
    invoices: [
      {
        invoiceNo: 'jra26045',
        invoiceDate: '2026-07-25',
        lines: [
          {
            poNo: '123456',
            styleNo: '654321',
            htsCode: '6104.69',
            pcs: '1,234',
            ctns: 30,
            cbm: '1.1',
            netWeightKg: 100,
            grossWeightKg: 110,
            fobUnitPrice: '1.5',
          },
          { poNo: '123456', styleNo: '654322', pcs: 1000, ctns: 20, fobUnitPrice: '2.125' },
        ],
      },
    ],
    declarations: [{ declareNo: 'e 41001', declareDate: '2026-07-30', portId: basics.port.id }],
    ...overrides,
  };
}

beforeEach(async () => {
  await resetDb();
  tokens = {};
  basics = await seedBasics();
});
afterAll(async () => {
  await pool.end();
});

describe('shipments', () => {
  it('creates a shipment with nested data, normalised values and a reference number', async () => {
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(await as('OPERATOR'))
      .send(exportShipment());
    expect(res.status).toBe(201);
    expect(res.body.reference).toMatch(/^SHP-26-\d{4}$/);
    expect(res.body.containers[0].containerNo).toBe('MRKU8974303');
    expect(res.body.invoices[0].invoiceNo).toBe('JRA26045');
    expect(res.body.invoices[0].lines[0].pcs).toBe('1234.000');
    // fob_amount is generated by PostgreSQL: 1234 × 1.5 and 1000 × 2.125
    expect(res.body.invoices[0].lines.map((l: { fobAmount: string }) => l.fobAmount)).toEqual([
      '1851.00',
      '2125.00',
    ]);
    expect(res.body.declarations[0]).toMatchObject({ declareNo: 'E 41001', hasLedgerEntry: false });
  });

  it('lists with totals and filters by client, direction and search text', async () => {
    const h = await as('OPERATOR');
    await request(app).post('/api/v1/shipments').set(h).send(exportShipment());
    await request(app)
      .post('/api/v1/shipments')
      .set(h)
      .send(
        exportShipment({
          clientId: basics.jyx.id,
          direction: 'IMPORT',
          transportMode: 'AIR',
          loadType: 'NONE',
          containers: [],
          invoices: [{ invoiceNo: 'CNG26040', lines: [{ pcs: 10, fobUnitPrice: 1 }] }],
          declarations: [],
        }),
      );
    const all = await request(app)
      .get('/api/v1/shipments')
      .set(await as('VIEWER'));
    expect(all.body.meta.total).toBe(2);
    const row = all.body.data.find((r: { clientCode: string }) => r.clientCode === 'JR');
    expect(row.totals).toMatchObject({ pcs: '2234.000', ctns: '50.000', fob: '3976.00' });
    expect(row.containers[0]).toMatchObject({ containerNo: 'MRKU8974303', size: '40HQ' });

    const byClient = await request(app)
      .get('/api/v1/shipments')
      .query({ clientId: basics.jyx.id })
      .set(h);
    expect(byClient.body.data.map((r: { invoiceNos: string[] }) => r.invoiceNos)).toEqual([
      ['CNG26040'],
    ]);
    const byDir = await request(app).get('/api/v1/shipments').query({ direction: 'EXPORT' }).set(h);
    expect(byDir.body.meta.total).toBe(1);
    const byContainer = await request(app).get('/api/v1/shipments').query({ q: '8974303' }).set(h);
    expect(byContainer.body.meta.total).toBe(1);
    const noMatch = await request(app).get('/api/v1/shipments').query({ q: '%' }).set(h);
    expect(noMatch.body.meta.total).toBe(0);
  });

  it('rejects business-rule violations with field paths', async () => {
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(await as('OPERATOR'))
      .send(
        exportShipment({
          transportMode: 'AIR',
          loadType: 'FCL',
          eta: '2026-07-01',
          containers: [{ containerNo: 'BAD1' }],
        }),
      );
    expect(res.status).toBe(400);
    const paths = res.body.error.details.map((d: { path: string }) => d.path);
    expect(paths).toEqual(expect.arrayContaining(['loadType', 'eta', 'containers.0.containerNo']));
  });

  it('refuses a duplicate invoice number with a clear message', async () => {
    const h = await as('OPERATOR');
    await request(app).post('/api/v1/shipments').set(h).send(exportShipment());
    const dup = await request(app)
      .post('/api/v1/shipments')
      .set(h)
      .send(exportShipment({ declarations: [] }));
    expect(dup.status).toBe(409);
    expect(dup.body.error.message).toBe('Invoice no. JRA26045 is already used on another shipment');
  });

  it('updates by replacing children and keeps the reference', async () => {
    const h = await as('MANAGER');
    const created = (await request(app).post('/api/v1/shipments').set(h).send(exportShipment()))
      .body;
    const res = await request(app)
      .put(`/api/v1/shipments/${created.id}`)
      .set(h)
      .send(
        exportShipment({
          status: 'COMPLETED',
          containers: [],
          loadType: 'LCL',
          invoices: [{ invoiceNo: 'JRA26046', lines: [{ pcs: 5, fobUnitPrice: 2 }] }],
          declarations: [
            { id: created.declarations[0].id, declareNo: 'E 41001', declareDate: '2026-07-31' },
          ],
        }),
      );
    expect(res.status).toBe(200);
    expect(res.body).toMatchObject({
      reference: created.reference,
      status: 'COMPLETED',
      containers: [],
    });
    expect(res.body.invoices.map((i: { invoiceNo: string }) => i.invoiceNo)).toEqual(['JRA26046']);
    expect(res.body.declarations[0]).toMatchObject({
      id: created.declarations[0].id,
      declareDate: '2026-07-31',
    });
  });

  it('protects declarations that have ledger entries', async () => {
    const h = await as('ADMIN');
    const created = (await request(app).post('/api/v1/shipments').set(h).send(exportShipment()))
      .body;
    await db.insert(accountingRecords).values({
      declarationId: created.declarations[0].id,
      clientId: basics.jr.id,
      invDate: '2026-07-31',
      exchangeRate: '4026',
    });
    const upd = await request(app)
      .put(`/api/v1/shipments/${created.id}`)
      .set(h)
      .send(exportShipment({ declarations: [] }));
    expect(upd.status).toBe(409);
    expect(upd.body.error.message).toContain('E 41001 has a ledger entry');
    const del = await request(app).delete(`/api/v1/shipments/${created.id}`).set(h);
    expect(del.status).toBe(409);
  });

  it('soft-deletes and hides the shipment; only roles with shipments:delete may delete', async () => {
    const created = (
      await request(app)
        .post('/api/v1/shipments')
        .set(await as('OPERATOR'))
        .send(exportShipment({ declarations: [] }))
    ).body;
    expect(
      (
        await request(app)
          .delete(`/api/v1/shipments/${created.id}`)
          .set(await as('OPERATOR'))
      ).status,
    ).toBe(403);
    expect(
      (
        await request(app)
          .delete(`/api/v1/shipments/${created.id}`)
          .set(await as('MANAGER'))
      ).status,
    ).toBe(204);
    expect(
      (
        await request(app)
          .get(`/api/v1/shipments/${created.id}`)
          .set(await as('MANAGER'))
      ).status,
    ).toBe(404);
    expect(
      (
        await request(app)
          .get('/api/v1/shipments')
          .set(await as('MANAGER'))
      ).body.meta.total,
    ).toBe(0);
  });

  it('viewers can read but not write', async () => {
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(await as('VIEWER'))
      .send(exportShipment());
    expect(res.status).toBe(403);
  });

  it('parses the real Export Template into invoices for the wizard', async () => {
    const res = await request(app)
      .post('/api/v1/shipments/parse-cargo-excel')
      .set(await as('OPERATOR'))
      .attach(
        'file',
        fs.readFileSync(path.join(DATA, 'export-template.xlsx')),
        'Export Template.xlsx',
      );
    expect(res.status).toBe(200);
    expect(res.body.invoices).toHaveLength(1);
    expect(res.body.invoices[0]).toMatchObject({
      invoiceNo: 'JRA26045',
      invoiceDate: '2026-09-10',
    });
    expect(res.body.invoices[0].lines).toHaveLength(5);
  });

  it('warns when an uploaded invoice number is already used', async () => {
    const h = await as('OPERATOR');
    await request(app).post('/api/v1/shipments').set(h).send(exportShipment());
    const res = await request(app)
      .post('/api/v1/shipments/parse-cargo-excel')
      .set(h)
      .attach(
        'file',
        fs.readFileSync(path.join(DATA, 'export-template.xlsx')),
        'Export Template.xlsx',
      );
    expect(res.body.warnings[0].message).toMatch(/JRA26045 is already on shipment SHP-26-/);
  });

  it('rejects non-spreadsheet uploads', async () => {
    const res = await request(app)
      .post('/api/v1/shipments/parse-cargo-excel')
      .set(await as('OPERATOR'))
      .attach('file', Buffer.from('hello'), { filename: 'notes.txt', contentType: 'text/plain' });
    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/\.xlsx or \.csv/);
  });

  it('exports the filtered list as xlsx', async () => {
    const h = await as('VIEWER');
    const res = await request(app)
      .get('/api/v1/shipments/export.xlsx')
      .set(h)
      .buffer(true)
      .parse((r, cb) => {
        const chunks: Buffer[] = [];
        r.on('data', (c: Buffer) => chunks.push(c));
        r.on('end', () => cb(null, Buffer.concat(chunks)));
      });
    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toContain('spreadsheetml');
    expect((res.body as Buffer).subarray(0, 2).toString()).toBe('PK'); // zip container
  });
});

describe('cut stock and CDC lines', () => {
  async function item(qty: string, name = 'ELECTRONIC SCALE-30KG') {
    const [row] = await db
      .insert(cutStockItems)
      .values({
        clientId: basics.jr.id,
        lineNo: 4,
        declareRef: 'I-4',
        category: 'MACHINERY_EQUIPMENT',
        name,
        unit: 'SET',
        qty,
        unitPrice: '50',
      })
      .returning();
    return row!;
  }
  const importWith = (
    itemId: string,
    qty: string,
    extra: Record<string, unknown> = {},
    declareNo = 'I 95001',
  ) =>
    exportShipment({
      direction: 'IMPORT',
      destinationCountryIso2: 'KH',
      originCountryIso2: 'CN',
      containers: [],
      loadType: 'LCL',
      invoices: [
        { invoiceNo: `CNG-${declareNo.replace(/\D/g, '')}`, lines: [{ pcs: 1, fobUnitPrice: 1 }] },
      ],
      declarations: [
        {
          declareNo,
          declareDate: '2026-08-20',
          cdcLines: [{ cutStockItemId: itemId, qty, unitPrice: '50', ...extra }],
        },
      ],
    });
  const balance = async (id: string) =>
    (
      await request(app)
        .get(`/api/v1/cut-stock/${id}`)
        .set(await as('VIEWER'))
    ).body as { balance: string; condition: string; movements: unknown[] };

  it('declaring an import reduces the balance', async () => {
    const it1 = await item('10');
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(await as('OPERATOR'))
      .send(importWith(it1.id, '6'));
    expect(res.status).toBe(201);
    expect(await balance(it1.id)).toMatchObject({ balance: '4.000', condition: 'CHECK' }); // 40 % < 50 %
    expect((await balance(it1.id)).movements).toHaveLength(1);
  });

  it('blocks over-imports and lists the violations', async () => {
    const it1 = await item('10');
    const h = await as('OPERATOR');
    await request(app).post('/api/v1/shipments').set(h).send(importWith(it1.id, '6'));
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(h)
      .send(importWith(it1.id, '5', {}, 'I 95002'));
    expect(res.status).toBe(422);
    expect(res.body.error.details).toEqual({
      rule: 'CUT_STOCK_OVER_IMPORT',
      violations: [
        {
          cutStockItemId: it1.id,
          itemName: 'ELECTRONIC SCALE-30KG',
          declareRef: 'I-4',
          balance: '4',
          requested: '5',
        },
      ],
    });
  });

  it('an override needs a Manager or Admin, and is recorded with who approved it', async () => {
    const it1 = await item('4');
    const body = importWith(it1.id, '5', {
      overrideReason: 'Customs approved extra unit (letter 12/08)',
    });
    expect(
      (
        await request(app)
          .post('/api/v1/shipments')
          .set(await as('OPERATOR'))
          .send(body)
      ).status,
    ).toBe(403);
    const ok = await request(app)
      .post('/api/v1/shipments')
      .set(await as('MANAGER'))
      .send(body);
    expect(ok.status).toBe(201);
    expect(ok.body.declarations[0].cdcLines[0].overrideReason).toMatch(/Customs approved/);
    const b = await balance(it1.id);
    expect(b.balance).toBe('-1.000');
    expect(b.movements[0]).toMatchObject({ overrideBy: 'Test MANAGER' });
  });

  it("rejects items from another client's master list", async () => {
    const it1 = await item('10');
    const res = await request(app)
      .post('/api/v1/shipments')
      .set(await as('OPERATOR'))
      .send({ ...importWith(it1.id, '1'), clientId: basics.jyx.id });
    expect(res.status).toBe(422);
    expect(res.body.error.message).toMatch(/another client/);
  });

  it('editing re-checks against the balance without double counting', async () => {
    const it1 = await item('10');
    const h = await as('OPERATOR');
    const created = (
      await request(app).post('/api/v1/shipments').set(h).send(importWith(it1.id, '6'))
    ).body;
    const decl = created.declarations[0];
    const upd = await request(app)
      .put(`/api/v1/shipments/${created.id}`)
      .set(h)
      .send({
        ...importWith(it1.id, '10'),
        declarations: [
          {
            id: decl.id,
            declareNo: decl.declareNo,
            declareDate: decl.declareDate,
            cdcLines: [{ cutStockItemId: it1.id, qty: '10' }],
          },
        ],
      });
    expect(upd.status).toBe(200);
    expect((await balance(it1.id)).balance).toBe('0.000');
  });

  it('deleting the shipment gives the quantity back', async () => {
    const it1 = await item('10');
    const created = (
      await request(app)
        .post('/api/v1/shipments')
        .set(await as('MANAGER'))
        .send(importWith(it1.id, '6'))
    ).body;
    await request(app)
      .delete(`/api/v1/shipments/${created.id}`)
      .set(await as('MANAGER'));
    expect((await balance(it1.id)).balance).toBe('10.000');
  });

  it('imports the real JR master list (dry run, apply, re-run) and exports it', async () => {
    const h = await as('OPERATOR');
    const file = fs.readFileSync(path.join(DATA, 'jr-cdc-master-list.xlsx'));
    const dry = await request(app)
      .post('/api/v1/cut-stock/import')
      .query({ clientId: basics.jr.id, dryRun: 'true' })
      .set(h)
      .attach('file', file, 'JR CDC MASTER LIST.xlsx');
    expect(dry.body).toMatchObject({ dryRun: true, created: 195, updated: 0, errors: [] });
    expect((await db.select({ n: sql<number>`count(*)::int` }).from(cutStockItems))[0]!.n).toBe(0);

    const applied = await request(app)
      .post('/api/v1/cut-stock/import')
      .query({ clientId: basics.jr.id, dryRun: 'false' })
      .set(h)
      .attach('file', file, 'JR CDC MASTER LIST.xlsx');
    expect(applied.body).toMatchObject({ created: 195 });
    const again = await request(app)
      .post('/api/v1/cut-stock/import')
      .query({ clientId: basics.jr.id, dryRun: 'false' })
      .set(h)
      .attach('file', file, 'JR CDC MASTER LIST.xlsx');
    expect(again.body).toMatchObject({ created: 0, updated: 0, unchanged: 195 });

    const list = await request(app)
      .get('/api/v1/cut-stock')
      .query({ clientId: basics.jr.id, condition: 'OVER' })
      .set(h);
    expect(list.body.summary).toMatchObject({ items: 195, overImported: 10 });
    expect(list.body.data).toHaveLength(10);
    const i10 = await db.select().from(cutStockItems).where(eq(cutStockItems.declareRef, 'I-10'));
    expect((await balance(i10[0]!.id)).balance).toBe('-24.000');

    const exp = await request(app)
      .get('/api/v1/cut-stock/export.xlsx')
      .query({ clientId: basics.jr.id })
      .set(h)
      .buffer(true)
      .parse((r, cb) => {
        const c: Buffer[] = [];
        r.on('data', (x: Buffer) => c.push(x));
        r.on('end', () => cb(null, Buffer.concat(c)));
      });
    expect(exp.status).toBe(200);
    expect(exp.headers['content-disposition']).toMatch(/JR-cdc-master-list/);
  });

  it('the picker returns balances for the shipment client', async () => {
    await item('10');
    const res = await request(app)
      .get('/api/v1/cut-stock/options')
      .query({ clientId: basics.jr.id, q: 'scale' })
      .set(await as('OPERATOR'));
    expect(res.body).toEqual([
      expect.objectContaining({ declareRef: 'I-4', balance: '10.000', unit: 'SET' }),
    ]);
  });
});

describe('clients', () => {
  it('creates, lists, updates and refuses deleting a client with shipments', async () => {
    const h = await as('OPERATOR');
    const created = await request(app)
      .post('/api/v1/clients')
      .set(h)
      .send({ code: 'sak', name: 'Sportline Garments', countryIso2: 'kh', commissionUsd: '50' });
    expect(created.status).toBe(201);
    const list = await request(app).get('/api/v1/clients').query({ q: 'sport' }).set(h);
    expect(list.body.data[0]).toMatchObject({
      code: 'SAK',
      countryName: 'Cambodia',
      shipmentCount: 0,
    });
    expect(list.body.data[0].netProfitYtd).toBeUndefined(); // operators can't see accounting

    const mgr = await request(app)
      .get('/api/v1/clients')
      .set(await as('MANAGER'));
    expect(mgr.body.data[0].netProfitYtd).toBe('0');

    await request(app)
      .post('/api/v1/shipments')
      .set(h)
      .send(exportShipment({ declarations: [] }));
    const del = await request(app).delete(`/api/v1/clients/${basics.jr.id}`).set(h);
    expect(del.status).toBe(409);
    const deact = await request(app)
      .patch(`/api/v1/clients/${basics.jr.id}`)
      .set(h)
      .send({ status: 'INACTIVE' });
    expect(deact.status).toBe(200);
    const blocked = await request(app)
      .post('/api/v1/shipments')
      .set(h)
      .send(exportShipment({ invoices: [], declarations: [] }));
    expect(blocked.status).toBe(422);
    expect(blocked.body.error.message).toMatch(/inactive/);
    expect((await request(app).delete(`/api/v1/clients/${created.body.id}`).set(h)).status).toBe(
      204,
    );
  });

  it('detail includes counts and recent shipments', async () => {
    const h = await as('MANAGER');
    await request(app).post('/api/v1/shipments').set(h).send(exportShipment());
    const res = await request(app).get(`/api/v1/clients/${basics.jr.id}`).set(h);
    expect(res.body).toMatchObject({
      code: 'JR',
      exportCount: 1,
      importCount: 0,
      shipmentCount: 1,
      activeShipments: 1,
    });
    expect(res.body.recentShipments[0].invoiceNos).toEqual(['JRA26045']);
  });

  it('rejects a duplicate client code', async () => {
    const res = await request(app)
      .post('/api/v1/clients')
      .set(await as('ADMIN'))
      .send({ code: 'JR', name: 'Another JR', countryIso2: 'KH', commissionUsd: 0 });
    expect(res.status).toBe(409);
  });
});

describe('lookups', () => {
  it('returns dropdown data and quick-adds a consignee', async () => {
    const h = await as('OPERATOR');
    const add = await request(app)
      .post('/api/v1/lookups/consignees')
      .set(h)
      .send({ name: 'Chapterone Sportswear', countryIso2: 'us' });
    expect(add.status).toBe(201);
    const res = await request(app)
      .get('/api/v1/lookups')
      .set(await as('VIEWER'));
    expect(res.body.clients.map((c: { code: string }) => c.code)).toEqual(['JR', 'JYX']);
    expect(res.body.consignees[0]).toMatchObject({
      name: 'Chapterone Sportswear',
      countryIso2: 'US',
    });
    expect(res.body.ports[0]).toMatchObject({ code: 'SHV11' });
  });
});
